### POST request to create new client entity
POST http://localhost:4000/clients
Content-Type: application/json

{
  "name" : "Winter",
  "email": "",
  "address": "43 main street",
  "dateOfBirth": "2020-09-09",
  "registeredDate": "2025-01-02"
}

###
